config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'
  get 'tasks/:id/edit' => 'tasks#edit', as: "task_edit"
  post 'task/:id/update' => 'tasks#update', as: "task_update"
  delete 'tasks/:id/delete' => 'tasks#delete', as: "task_delete"
  post 'line/bot'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/line_controller.rb
#linebotapiのインポート
require 'line/bot'

class LineController < ApplicationController

  #Railsのあるセキュリティ対策を無効化
  protect_from_forgery :except => [:bot]

  #LINEでメッセージを送るとこのアクションメソッドbotが走る
  def bot
    #LINEで送られてきたメッセージのデータを取得
    body = request.body.read

    #LINE以外からのアクセスの場合エラーを返す
    signature = request.env['HTTP_X_LINE_SIGNATURE']
    unless client.validate_signature(body,signature)
      head :bad_request
    end

    #LINEで送られてきたメッセージのデータeventsというデータ構造に変更
    events = client.parse_events_from(body)

    #eventsの中身を舐める
    events.each {|event|
      #eventがメッセージだったら
      case event
      when Line::Bot::Event::Message
        #メッセージのタイプがテキストだったら（スタンプ等ではなく）
        case event.type
        when Line::Bot::Event::MessageType::Text

        #メッセージの文字列を取得して、変数taskに代入
        task = event['message']['text']

        #DBへの登録処理開始
        begin
          #メッセージの文字列をタスクテーブルに登録
          Task.create!(task: task)

            #登録に成功した場合、登録した旨をLINEで返す
            message = {type: 'text', text: "タスク『#{task}』を登録しました！"}
            client.reply_message(event['replyToken'], message)
          rescue

            #登録に失敗した場合、登録に失敗した旨をLINEで返す
            message = {type: 'text', text: "タスク『#{task}』の登録に失敗しました。"}
            client.reply_message(event['replyToken'], message)
        end
      end
    end
    }
    head :ok
  end

  #LINEボットを生成して返すプライベートメソッドの定義
  private

  def client
    @client ||= Line::Bot::Client.new{|config|
      #サーバに事前に登録したチャネルシークレットとチャネルトークンをセット
    config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
    config.channel_token = ENV["LINE_CHANNEL_TOKEN"]}
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def edit 
   @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.task = params[:task]
    if task.save
      redirect_to tasks_index_path, notice: "タスクを1件更新しました"
    else
      redirect_to tasks_index_path, alert: "タスクの更新に失敗しました"
    end
  end

  def delete
    task = Task.find(params[:id])
    if task.destroy
      redirect_to tasks_index_path, notice: "タスクを1件削除しました"
    else
      redirect_to tasks_index_path, alert: "タスクの削除に失敗しました"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineTodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
  <body class="container">
    <% if notice.present? %>
    <aside class="alert alert-info">
     <%= notice %>
     </aside>
    <% end %>
    <% if alert.present? %>
    <aside class="alert alert-danger">
     <%= alert %>
     </aside>
    <% end %>
    <%= image_tag "udon.png", style: "vertical-align: bottom; margin: 10px; width: 100px;"%>
    <%= yield %>
  </body>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1 class="h4">タスク編集画面</h1>
<%= form_tag(task_update_path, method: :post) do %>
  <div class="form-group">
  <%= text_area_tag :task, @task.task, class:"form-control" %>
  </div>
  <div class="actions pt-2 pb-5">
    <%= submit_tag "編集", class:"btn btn-primary" %>
    <%= link_to '一覧画面',tasks_index_path, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="3" class="h4">タスク</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |t| %>
      <tr>
        <td><%= t.task %></td>
        <td>
          <%= link_to "編集", task_edit_path(t), class:"btn btn-primary" %>
        </td>
        <td>
          <%= link_to "削除", task_delete_path(t), method: :delete, data: {confirm: "本当に削除しますか？"}, class:"btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>